### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by bobvmierlo** [MrSuicideParrot/Kaspersky-Password-Manager-to-CSV#1]
Hi,

The python script has been running for hours with 30% CPU and 4gb of RAM usage. Still no output to CSV file. Is this still a working script?

**Comment by MrSuicideParrot** [comment]
Hi!
Sorry for the delay.
I don't know if the format of the karspersky password manager is the same. I created this script when I stopped using this password manager. 
Do you still have this problem? 
I can try to find out if the program is still working....

**Comment by bobvmierlo** [comment]
Hi!
No problem ;) no rush.
To answer your question, yes the problem still persists. Script runs for our without any output.
I'm not very good at python so debugging isn't something I managed to do.
Would very much like this to work though.

**Comment by MrSuicideParrot** [comment]
I think my script now works for the new export format, can you check it out?

**Comment by bobvmierlo** [comment]
I've run your new script for about 10 minutes now at 45% CPU and 4gb of RAM usage. Although no output yet. Could it be that my export is different because my Kaspersky is in Dutch? The export seems to be formatted in english though..

Here is a part of the export (anonymised ofcourse)

```
Websites

Website name: eurosparen.nl
Website URL: eurosparen.nl
Login name: 
Login: XXXXXXXX
Password: XXXXXXXX
Comment: 

---

Website name: biermaster.nl
Website URL: biermaster.nl
Login name: 
Login: XXXXXXXX
Password: XXXXXXXX
Comment: 

---
```

**Comment by MrSuicideParrot** [comment]
I think that the country is not a problem... I have a check to verify special characters like _ç_...
What are the type of credential that appear on the output file?
The testing files that I used have Websites, Notes and Applications... Do you have another category??

**Comment by MrSuicideParrot** [comment]
I think the country is not a problem, if you are referring to special characters...  
What are the credential types that you have on the output file?
The test files I used have the following categories: Websites, Applications and Notes.
The program is only prepared for this order and categories. 
Do you have anything different?

**Comment by bobvmierlo** [comment]
The issue was that I didn't have anything in the "Applications" section. Added something to fill this section and the script finished in 2 seconds. It did not export my Notes though.

**Comment by MrSuicideParrot** [comment]
Thank you very much!
The file that doesn't have the "application" section goes directly for the "notes" section?
I want to fix this problem...

**Comment by bobvmierlo** [comment]
Without the applications section the script just keeps on running for hours with no output. So then I put some fake input in the applications section, then the script ran fine within 2 seconds. But somehow it did not put the notes section in the CSV file.

**Comment by MrSuicideParrot** [comment]
This program doesn't export the notes section. Because the notes do not have the same  fields of a password or application...

**Comment by MrSuicideParrot** [comment]
I think that now the program is prepare to receive a file without the application section.
Can you confirm?
